### ISSUE TITLE
not working on ipad

### ISSUE THREAD

**Issue by russellu** [GracesGames/SimpleFileBrowser#19]
the file browser just shows empty when using on ipad.

works for android, windows, and osx however. is there some permission i have to set for ipad?

**Comment by GracesGames** [comment]
Hmm this would be very difficult for me to test without an iPad (only have Windows, OS X and Android).
I'll try to do some research, maybe it is a more common problem.

**Comment by GracesGames** [comment]
This is most likely a permissions issue based on setup (xcode permissions or an additional file in Unity), so not something I can fix in the project. Closing this issue for now, good luck.
