### ISSUE TITLE
[Demo Scene] Error on saving empty file

### ISSUE THREAD

**Issue by as3mbus** [GracesGames/SimpleFileBrowser#2]
hey. i really like this project that u made and im planning to use it for my own project that create a story and play it when needed through json. 
tried the demo scene and work rly gud even on linux editor
but there r some error i encountered when saving empty file. 

just to let you know i put up some image and also the output error.

thx 4 sharing this project btw 👍 i'll try contribute to the project while im using it as well

![image](https://user-images.githubusercontent.com/16043293/31055207-00b16546-a6ea-11e7-844a-309abe2393a7.png)

`ArgumentNullException: Argument cannot be null.
Parameter name: obj
System.Runtime.Serialization.ObjectIDGenerator.GetId (System.Object obj, System.Boolean& firstTime) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.Serialization/ObjectIDGenerator.cs:82)
System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteObjectInstance (System.IO.BinaryWriter writer, System.Object obj, Boolean isValueObject) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.Serialization.Formatters.Binary/ObjectWriter.cs:284)
System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteQueuedObjects (System.IO.BinaryWriter writer) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.Serialization.Formatters.Binary/ObjectWriter.cs:271)
System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteObjectGraph (System.IO.BinaryWriter writer, System.Object obj, System.Runtime.Remoting.Messaging.Header[] headers) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.Serialization.Formatters.Binary/ObjectWriter.cs:256)
System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph, System.Runtime.Remoting.Messaging.Header[] headers) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.Serialization.Formatters.Binary/BinaryFormatter.cs:232)
System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize (System.IO.Stream serializationStream, System.Object graph) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.Serialization.Formatters.Binary/BinaryFormatter.cs:211)
GracesGames.DemoCaller.SaveFileUsingPath (System.String path) (at Assets/Extern/SimpleFileBrowser/SimpleFileBrowser/Scripts/GracesGames/DemoCaller.cs:71)
UnityEngine.Component:SendMessage(String, Object)
GracesGames.FileBrowser:SendCallbackMessage(String) (at Assets/Extern/SimpleFileBrowser/SimpleFileBrowser/Scripts/GracesGames/FileBrowser.cs:244)
GracesGames.FileBrowser:SelectFile() (at Assets/Extern/SimpleFileBrowser/SimpleFileBrowser/Scripts/GracesGames/FileBrowser.cs:234)
UnityEngine.EventSystems.EventSystem:Update()
`

**Comment by GracesGames** [comment]
Issue should be solved on master now, will release a version for Unity Asset Store soon.
Thanks for reporting the bug and your future contributions :)

**Comment by as3mbus** [comment]
probably gonna use the git version more :)
thx 4 the quick reply :)
