### ISSUE TITLE
Static method or variable for open file window

### ISSUE THREAD

**Issue by TheRealCatherine** [GracesGames/SimpleFileBrowser#28]
This is a feature request to be able to statically call something like
if(FileBrowser.IsOpen()) {
//dont handle keypress
}

I did a quick and dirty version here: https://github.com/TheRealCatherine/StageMechanic/commit/31f0d1ff0d2bcd1150b63e3be28a44ba741fb7cb

so no immediate need but of course modifying 3rd party stuff makes updates difficult so hopefully it becomes a feature in the official version <3

**Comment by GracesGames** [comment]
Let me know if the Pull Request fixes this issue

**Comment by TheRealCatherine** [comment]
I will check but actually I found a bug in my version code that can cause Unity Editor to crash randomly when opening the dialogs. I think this commit fixes it:

https://github.com/TheRealCatherine/StageMechanic/commit/1c80578a626d2b632632dd6fae66a1fb53c9b3b9

even though there is no obvious reason that it would that I can see - but so far this change has kept Unity from randomly crashing when opening a file dialog. I'll test it for a couple more days and let you know for sure if it fixes it.

**Comment by TheRealCatherine** [comment]
Hmm for some reason I'm getting random crashes when using Unity Editor any time I open a file dialog since implementing this. I will need to investigate the cause but it seems totally random - sometimes works fine and other times not. I'll play around with it the next few days and see if I can get if fixed and let you know.

**Comment by TheRealCatherine** [comment]
Ok Unity Support tested it and said that it is fixed in the upcoming 2018.1 beta but there seem to be no plans to fix the underlying cause of the crash in 20017.3

**Comment by GracesGames** [comment]
Any information on the underlying cause?
I use a static variable (private with public method) in other projects and never had any problems.
Could it be the public static variable part?

**Comment by GracesGames** [comment]
@TheRealCatherine I am thinking about making the IsOpen method non-static, since the FileBrowser script is not a singleton (it should support multiple instances i guess, have not tested that). That would probably also solve the crashes. Love to hear your opinion.

**Comment by TheRealCatherine** [comment]
Hi there, I can confirm that its fixed in 2018.1beta. I think there was a weird race condition happening in the Unity Editor involving coroutines and static variables but I didn't spend too much time on it since its fixed now (and it was only happening when running in editor, not in standalone player)

Regarding making it non-static - at least in my project there is only ever one file browser open so for my needs making it static is easier but perhaps instead of IsOpen you could have like public static int NumberOfOpenBrowsers() which would return 0 if none are open and 1+ if one or more are open.

The reason I'm using it is so that my input handler classes can make sure there is no open file dialog before processing user input - otherwise every time the user types into the file dialog it also gets processed as key presses in the application (and lots of keys map to keyboard shortcuts for us) so I can do like:

 Update() {
 if(FileBrowser.IsOpen())return;
 if(Input.GetKey(....blahblah
}

but this could easily be if(FileBrowser.OpenWindowCount()>0) or something

but of course my input handling code is in a way different place than where the file dialogs are opened so a static method in FileDialog is, as far as I see, the cleanest way to get this information. I'm open to suggestions though if you have another idea.

**Comment by GracesGames** [comment]
Thank you for the clarification, I have a better understanding of the problem now.

Keeping track of open File Browsers should not be a responsibility of the FileBrowser script, but the CallerScript. So whichever script is instantiating the FileBrowser Prefab should keep a (static) index of open file browsers and reduce this value in the callback method. Then you can use `CallerScript.OpenFileBrowsers() == 0`.

Most project will indeed allow only a single file browser, yet I do not want to exclude projects that allow multiple file browsers to be open simultaneously.

**Comment by TheRealCatherine** [comment]
Well I considered that when I first introduced this change but the issue I see with having the calling script keep track of open file windows is that it has no way to know about potential problems or, for example, if Cancel is changed to just not call callbacks instead of calling them with a null string. With the callback pattern used the callback method, IMHO, shouldn't be responsible for the state of the caller and the caller may have no way of knowing if the callback was called (since thats a feature of callback patterns, that it shouldn't matter to the caller if the callback even has subscribers)

To me, the most sensible method is to have FileBrowser just have a static int with the number of open windows that can be retrieved, since it is directly responsible for creating and destroying the windows - so replacing IsOpen with like NumberOfOpen

**Comment by GracesGames** [comment]
While the FileBrowser script is responsible for creating and destroying its UI, the instance should not keep track of how many windows there are. 
It would also make the method very unclear when there are multiple FileBrowser scripts active since both will then count the number of open windows.

I will add the IsOpen method to the FileBrowser script for the caller to see if the instance is open (#32), but there will be no accounting of File Browser windows implemented in the FileBrowser script.
