### ISSUE TITLE
Allow setting starting path

### ISSUE THREAD

**Issue by TheRealCatherine** [GracesGames/SimpleFileBrowser#29]
This is a feature request to allow the user to set the starting path when the window opens. I have implemented a version of it in this code and would love to see this feature included in the official version. In our project we are using it to set the default directory to be the same as the last directory loaded/saved from.

See this commit: https://github.com/TheRealCatherine/StageMechanic/commit/e0775d260a9a6409e9fa9aa4871631c2893199c2

for the modifications we did to FileBrowser

**Comment by GracesGames** [comment]
Let me know if the Pull Request fixes this issue

**Comment by TheRealCatherine** [comment]
Yes that looks good to me!
