### ISSUE TITLE
Blank on android

### ISSUE THREAD

**Issue by Polaris00418** [GracesGames/SimpleFileBrowser#34]
### Question, bug or feature

It was just empty black page on my Samsung s8

### Version(s) affected

1.3.0 version released Jan 18, 2018

### Unity version

2017.3.0p3

### Steps to reproduce

How to reproduce the issue

**Comment by GracesGames** [comment]
Found a similar case on the Store Page review section: For anyone who have the same problem: I had to remove maxsdkversion in read and write permission in the AndroidManifest manually by replacing unity's default AndroidManifest. 
So probably a permission issue. Could you check the app had read/write permission to internal and external storage?

**Comment by TheRealCatherine** [comment]
The first time I tried deploying it on Android I had a blank browser also, but it was because of the external storage permission not being set in the unity android build settings. Definitely worth double checking that.

**Comment by GracesGames** [comment]
Should be solved then, closing this issue
