### ISSUE TITLE
how do i Instantiate the file browser??

### ISSUE THREAD

**Issue by PaulNicolasHunter** [GracesGames/SimpleFileBrowser#39]
Which version of the Simple File Browser is used?
current ver. 1.4.0

### Unity version
5.6

### Screenshot(s)
![screenshot 33](https://user-images.githubusercontent.com/26624903/40573240-8e729dae-60db-11e8-8de5-6d204d325e22.png)

Screenshots to illustrate the issue

hi! i'm new to Unity , and what i want is that to open the file explorer to open when the button is clicked and i only want to load images using this. 

so for that i do following steps.

1. make an game object and attached my modified script to it.
2. attach that gameObject to the Clickon() of the button and then on the function i call the openbrowser() function.

but i'm getting an error that the filebrowserprefab needs to be assigned.
````
using System.Collections;
using UnityEngine.UI;
using System.Collections.Generic;
using UnityEngine;
using System.Runtime.Serialization.Formatters.Binary;
using System.IO;
using System;

namespace GracesGames.SimpleFileBrowser.Scripts
{
    public class explorer_script : MonoBehaviour
    {
        public GameObject FileBrowserPrefab;
        public string[] FileExtensions = { "jpeg", "jpg", "png" };
        private GameObject _loadedImage;
        public RawImage image;
        public bool PortraitMode;
        void start()
        {
            
            PortraitMode = true;
        }

        public void OpenFileBrowser()
        {
            OpenFileBrowser(FileBrowserMode.Load);
        }

        private void OpenFileBrowser(FileBrowserMode fileBrowserMode)
        {
            FileBrowserPrefab = GameObject.Find("GameObject");
            // Create the file browser and name it
            GameObject fileBrowserObject = Instantiate(FileBrowserPrefab, transform);
            fileBrowserObject.name = "FileBrowser";
            // Set the mode to save or load
            FileBrowser fileBrowserScript = fileBrowserObject.GetComponent<FileBrowser>();
            fileBrowserScript.SetupFileBrowser(PortraitMode ? ViewMode.Portrait : ViewMode.Landscape);
 
            fileBrowserScript.OpenFilePanel(FileExtensions);
            fileBrowserScript.OnFileSelect += LoadFileUsingPath;
 
        }

        // Loads a file using a path
        private void LoadFileUsingPath(string path)
        {
            if (path.Length != 0)
            {
                BinaryFormatter bFormatter = new BinaryFormatter();
                // Open the file using the path
                FileStream file = File.OpenRead(path);
                // Convert the file from a byte array into a RawImage
                RawImage fileData = bFormatter.Deserialize(file) as RawImage;
                // We're done working with the file so we can close it
                file.Close();
                
            }
            else
            {
                Debug.Log("Invalid path given");
            }
        }
    }
}

i know it might not be an issue but guidance will be graceful.

**Comment by PaulNicolasHunter** [comment]
can you tell me where i'm getting it wrong? and how to setup it correctly?

**Comment by GracesGames** [comment]
From the data you posted I assume it's these two lines:

```
 FileBrowserPrefab = GameObject.Find("GameObject");
// Create the file browser and name it
GameObject fileBrowserObject = Instantiate(FileBrowserPrefab, transform);
```

As shown in the DemoCaller prefab, the FileBrowser prefab should be linked to the caller object so it can be properly instantiated. Example:

![image](https://user-images.githubusercontent.com/27864009/40575933-a0e6517a-60ee-11e8-8871-41942a7668b6.png)

You set the prefab to `GameObject.Find("GameObject");`, which I assume is not a proper FileBrowserPrefab object, but if it is I would need more information.

Hope that solves your problem.

Quick question, I this also your question: 

![image](https://user-images.githubusercontent.com/27864009/40575942-ce68cd76-60ee-11e8-882f-ea2566b79fca.png)

**Comment by PaulNicolasHunter** [comment]
okay so suddenly it has starting working, but now the problem is that preview is more than size of the canvas. how do it adjust that?

**Comment by GracesGames** [comment]
You can set your canvas size in the canvas component:

![image](https://user-images.githubusercontent.com/27864009/40576263-35a858cc-60f3-11e8-8de0-182a6412d290.png)

You can set the scale of the Simple File Browser UI in the FileBrowserLandscapeUI/FileBrowserPortraitUI:

![image](https://user-images.githubusercontent.com/27864009/40576270-67d9a288-60f3-11e8-9317-e1385cb8fc00.png)

Or change the values of the panel in the FileBrowserPanel (child of FileBrowserLandscapeUI) :

![image](https://user-images.githubusercontent.com/27864009/40576284-a2ecfff0-60f3-11e8-8fda-12e11985666f.png)

Hope that answers your question.

**Comment by PaulNicolasHunter** [comment]
thank you so much :)

**Comment by GracesGames** [comment]
Sure thing :) 
Good luck with your product and hope the Simple File Browser satisfies your needs.
Maybe even so much that you change the rating from 4 to 5 stars ;)

**Comment by PaulNicolasHunter** [comment]
i already did :) , by the way i have another little doubt that will it work for uploading images? like in the `demoscript `we have a `textfield `but what about raw_image? what i have done is that I have changed a line like this ` RawImage fileData = bFormatter.Deserialize(file) as RawImage;`  instead of `string fileData = bFormatter.Deserialize(file) as string;` because i want a to upload image, so is this an right approach or is there any other way to do so?

**Comment by GracesGames** [comment]
Thanks :)

I have no experience with RawImage yet.
It really depends on the use case, where you want to save it and which elements (maybe just the texture, which can be converted to a byte[]. This data can be saved for sure).

Else I'm sure Google and Unity Answers can help you.

**Comment by PaulNicolasHunter** [comment]
Sorry to bother you again, and yea you were right i am now able to resize it thanks to you, but now the problem is that the navigation buttons aren't working on my phone, but it perfectly works on my PC when i try it in game mode, i'm using android Samsung J7, what could be the reason?

Here are the screen shots of the screen,

So, the first screen shot is where there is button which instantiates the script (opens up the explorer), 
![screenshot_20180529-161321 1](https://user-images.githubusercontent.com/26624903/40654318-913dbb72-635b-11e8-8149-67af0ddbf315.png)

and in the second screen opens up, but i can't use the back arrows to go back and fourth.
![screenshot_20180529-161329 1](https://user-images.githubusercontent.com/26624903/40654353-b0e14a5c-635b-11e8-91b4-8f5fc909f503.png)

there is not even path named "storage/emulator0" on my phone man.
any guesses?
thanks

**Comment by PaulNicolasHunter** [comment]
Alright, so i found a solution for this, actually i was supposed to add android manifest, and add "android.permission.READ_EXTERNAL_STORAGE" as a manifest, but now my another problem is that once i close the explorer , i can't open it again by pressing the button again..

**Comment by PaulNicolasHunter** [comment]
yeah, but as we know that DEVICE STORAGE and  SD CARD are like two separate storage entities, and as i talked earlier that "storage/emulated/0" is the source which i have no idea, then how are we supposed to navigate between the two separate storage?

i don't think it's really much difference in the scripts, in your `LoadFileUsingPath` instead of loading the string in the file, i have sent that path to a firebase function which just accepts the path of the image and uploads it to cloud storage. if assuming that `fileBrowserScript.OnFileSelect += LoadFileUsingPath; ` calls the `LoadFileUsingPath` function by just passing a path to it.

the firebase uses Internet to execute so i added the INTERNET manifest too, but still that download button doesn't work (but it does works on my computer), 

moreover when i close the explorer, i can't reopen it again by re-pressing the button again (both in phone and PC).

what do you think could be the issue?

**Comment by GracesGames** [comment]
I use the file browser myself and known other users that have none of these problems.
It would be helpful to post some error code (debug mode in Unity) or gifs of what is happening. 
With the currently description it is quite unclear what the cause would be.

**Comment by PaulNicolasHunter** [comment]
Hi, thanks for replying here is the script i wrote, as i told you most of the things are same, just i access my storage using the path that SimpleFileBrowser gave me instead of reading the file into a byte array..

```
using System.Collections;
using UnityEngine.UI;
using System.Collections.Generic;
using UnityEngine;
using System.Runtime.Serialization.Formatters.Binary;
using System.IO;
using System;
using Firebase;
using Firebase.Storage;
using Firebase.Unity.Editor;
using System.Threading.Tasks;
using Firebase.Database;

namespace GracesGames.SimpleFileBrowser.Scripts
{
    public class explorer_script : MonoBehaviour
    {
        public GameObject FileBrowserPrefab;
        public string[] FileExtensions = { "jpeg", "jpg", "png" };
        private GameObject _loadedImage;   
        private bool PortraitMode;
        Texture2D tex;
        byte[] fileData;
        DatabaseReference reference;
        private string path_app = "/storage/emulated/0/MyAppdata/images";
        void Start()
        {

            PortraitMode = true;
            if (!Directory.Exists(path_app))
            {
                Directory.CreateDirectory("/storage/emulated/0/MyAppdata");
            }
            Directory.CreateDirectory("/storage/emulated/0/MyAppdata");

        }
        public void OpenFileBrowser()
        {
        
            GameObject fileBrowserObject = Instantiate(FileBrowserPrefab, transform);
            fileBrowserObject.name = "heyaa";
            // Set the mode to save or load
            FileBrowser fileBrowserScript = FileBrowserPrefab.GetComponent<FileBrowser>();

            if (fileBrowserScript == null)
            {

                Debug.LogError("script not found!");
            }

            fileBrowserScript.SetupFileBrowser(PortraitMode ? ViewMode.Portrait : ViewMode.Landscape);

            fileBrowserScript.OpenFilePanel(FileExtensions);
            fileBrowserScript.OnFileSelect += LoadFileUsingPath;

        }
        private void LoadFileUsingPath(string path)
        {

            if (File.Exists(path))
            {

                FireMan(path);
            }

            else
            {
                Debug.Log("error");
            }
        }

        public void FireMan(string path)
        {
           // HERE I ACCESS MY STORAGE TO PUT THE IMAGES USING THE PATH SimpleFileBrowser GAVE ME ;)
            Firebase.Storage.FirebaseStorage storage = Firebase.Storage.FirebaseStorage.DefaultInstance;

            Firebase.Storage.StorageReference storage_ref = storage.GetReferenceFromUrl("gs://path");

            Firebase.Storage.StorageReference art_image_ref = storage_ref.Child("images/innocence.jpg");

            art_image_ref.PutFileAsync(path).ContinueWith((Task<StorageMetadata> task) =>
            {
                if (task.IsFaulted || task.IsCanceled)
                {
                    Debug.Log(task.Exception.ToString());
                    // Uh-oh, an error occurred!
                }
                else
                {
                    // Metadata contains file metadata such as size, content-type, and download URL.
                    Firebase.Storage.StorageMetadata metadata = task.Result;
                    string download_url = metadata.DownloadUrl.ToString();
                    Debug.Log("Finished uploading...");
                    Debug.Log("download url = " + download_url);
                }
            });
        }
    }
}
```

**Comment by GracesGames** [comment]
Yeah that looks indeed quite similar.
To really solve the problem, the code is not that helpful right now.
An error log or some gifs would clarify the problem probably and allow others to help you.

**Comment by PaulNicolasHunter** [comment]
there is no error log my friend, it works totally fine on my computer, i'm able to select the images and they are being uploaded to firebase, the only problem is with android.

**Comment by GracesGames** [comment]
Please understand that while I do support my tool, this is outside of the support scope.
A quick google search gave this: https://support.unity3d.com/hc/en-us/articles/205485376-How-do-you-debug-on-Android-

**Comment by PaulNicolasHunter** [comment]
thank you so much for help friend bless you
