### ISSUE TITLE
How can I set the LoadDialog window scale? It doesn't fit on my Android screen

### ISSUE THREAD

**Issue by rodcibils** [GracesGames/SimpleFileBrowser#40]
It's possible to set the dialog's size or scale it (according to the current screen resolution on an Android Phone)? It's the first time i use this Asset and at this time i can't find how to do it on the docs. 

Thanks!

**Comment by GracesGames** [comment]
You can set your canvas size in the canvas component:

![image](https://user-images.githubusercontent.com/27864009/40741583-3073e068-644c-11e8-863e-d6e1bb900799.png)

You can set the scale of the Simple File Browser UI in the FileBrowserLandscapeUI/FileBrowserPortraitUI:

![image](https://user-images.githubusercontent.com/27864009/40741594-37fbc4d6-644c-11e8-9aed-bcf8d922059d.png)


Or change the values of the panel in the FileBrowserPanel (child of FileBrowserLandscapeUI) :

![image](https://user-images.githubusercontent.com/27864009/40741603-3da5c544-644c-11e8-878d-1b2372f7d91e.png)

Hope that answers your question.

**Comment by rodcibils** [comment]
Thanks for the fast answer! It's been a good solution for me, I'll close this issue.
