### ISSUE TITLE
Natural Sorting

### ISSUE THREAD

**Issue by TheRealCatherine** [GracesGames/SimpleFileBrowser#41]
Currently if you have files name like 1.json, 2.json ... 10.json .. 20.json you get:

1.json
10.json
2.json
20.json
3.json
4.json
5.json

we have fixed this in the linked patch to have it list as:

1.json
2.json
3.json
...
10.json
11.json
12.json
...
20.json

https://gitlab.com/youreperfectstudio/StageMechanic/commit/62bf99a8a44059941f4e28b7885c66f5205d59e3

**Comment by GracesGames** [comment]
Thanks for the suggestion and example, I'll try to integrate this feature in the near future

**Comment by GracesGames** [comment]
Have you been able to test the PR branch/version. Once it works, I'll release a patch release

**Comment by TheRealCatherine** [comment]
No I haven't, our codebase has diverged somewhat from yours. In a later version we will try and move our changes externally or do them in a way that can be easily upstreamed.

**Comment by GracesGames** [comment]
Ok no problem. I have added a screenshot of the result. 
I'll review, merge and release a new version next week or the week after.

**Comment by TheRealCatherine** [comment]
FWIW the screenshot looks fine :-)
