### ISSUE TITLE
No files showing in android

### ISSUE THREAD

**Issue by Fr0stM0urne** [GracesGames/SimpleFileBrowser#42]
### Question, bug or feature

Files are not showing in the browser when Demo Scene is build on Andriod. Browser gets stuck on storage/emulated/0. Android does not ask for permission to be read files. A previous thread mentioned adding permissions in the manifest and enabling external read permission in unity player settings. I tried that but the browser is still blank. I am using an S8. The thread also mentioned removing maxsdkversion but there is no thing like that in my AndriodManifest file.

### Version(s) affected

Simple File Browser Version: 1.4.0

### Unity version

Unity Version: 2018.1.1f1

### Steps to reproduce

1. Build Demo Scene. 
2. Click load file button.

Browser will be stuck at storage/emulated/0. Navigation buttons do not work. No files will be shown.

**Comment by GracesGames** [comment]
Could this be a duplicate of: https://github.com/GracesGames/SimpleFileBrowser/issues/34 ?
Hope that setting the AndroidManifest etc. resolves the problem. If not, let me know :)

**Comment by Fr0stM0urne** [comment]
I tried all of the fixes mentioned there but the browser is still blank. I used this AndriodManifest file:
![andmanifest](https://user-images.githubusercontent.com/33102679/42445440-8b9561ce-838c-11e8-9843-23a3aafdc9cd.PNG)
Can you send me a manifest file if this one is not correct? I copied this file in Assets/Plugins/Andriod in Unity.

**Comment by Fr0stM0urne** [comment]
I have added Google ARCore SDK Package in my Unity project. I removed that now it is working. Could find a way to use it with ARCore?

**Comment by Fr0stM0urne** [comment]
Ok. I fixed it by adding your package first then after added Google ARCore. Then used AndroidPermissionManager that comes with Google ARCore to add the required permissions. Although I think adding the permission in the AndriodPermssionManager did not do anything but changing the order in which unity packages are imported worked. You have first import the file browser package and build the app. Then add Google ARCore.

**Comment by GracesGames** [comment]
Hmm never experienced or heard anything like this, thanks for the update and glad to hear that it works now :)
