### ISSUE TITLE
Not show file hierarchy in browser

### ISSUE THREAD

**Issue by hammadalibutt** [GracesGames/SimpleFileBrowser#48]
### Question, bug or feature

Please attach the label accordingly

### Version(s) affected

Which version of the Simple File Browser is used?

### Unity version

Which version of Unity is used?

### Screenshot(s)

Screenshots to illustrate the issue

### Steps to reproduce

How to reproduce the issue

**Comment by hammadalibutt** [comment]
Browser open on default address /storage/emulated/0 and shows nothing in file and directory panel. Both panel remain empty so nothing could be select or save.

**Comment by GracesGames** [comment]
Could #34 or #42 help with the problem? 

or 

![image](https://user-images.githubusercontent.com/27864009/44536702-581c8180-a6fd-11e8-8216-f1c8f566597b.png)

Heard this before and almost always an external setting.

**Comment by GracesGames** [comment]
Any update? Else I'll close this issue in a week

**Comment by GracesGames** [comment]
That's seems more like an mobile OS issue than an issue of the SimpleFileBrowser. 
For me that happened automatically with the manifest and Unity settings. 
Good luck

**Comment by hammadalibutt** [comment]
Hey,

I just signed the petition "End Female Genital Mutilation in India" and
wanted to see if you could help by adding your name.

Our goal is to reach 191,365 signatures and we need more support. You can
read more and sign the petition here:

https://chn.ge/2OOqsKh

Thanks!
Hammad

**Comment by hammadalibutt** [comment]
Hey,

I just signed the petition "Office of the High Commissioner for Human
Rights: URGENT PETITION ON THE UN KASHMIR REPORT" and wanted to see if you
could help by adding your name.

Our goal is to reach 200,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/JTMdjF7Vfn

Thanks!
Hammad

**Comment by hammadalibutt** [comment]
Hey,

I just signed the petition "Unicef : Remove Priyanka Chopra as UN Goodwill
Peace Ambassador" and wanted to see if you could help by adding your name.

Our goal is to reach 150,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/ZjXJKjdsWd

Thanks!
Hammad
