### ISSUE TITLE
File browser sizing issue in Unity Editor

### ISSUE THREAD

**Issue by TheRealCatherine** [GracesGames/SimpleFileBrowser#6]
When launching the open or save dialogs in Unity Editor (versus using the stand-along player) there seems to be a sizing issue preventing the full dialog from displaying unless I increase the size of the editor view window.

I'm using Windows 10 at 1080p resolution. In this case Unity is not maximized, but is almost full screen:
![image](https://user-images.githubusercontent.com/31754592/31530200-6089ef5c-afa4-11e7-9f7e-e5331ae0ee20.png)

In this case I made Unity editor maximized and lowered the panels at the bottom as much as possible and it allows the dialogs to be used just barely (the file list in this one is blank, thats normal in this case, this is just about the sizing)

![image](https://user-images.githubusercontent.com/31754592/31530231-a80df350-afa4-11e7-8b8d-478a7625778e.png)

The code I use to open them, I believe, is pretty standard:

`public void SaveToJson() {
		GameObject fileBrowserObject = Instantiate(FileBrowserPrefab, this.transform);
		fileBrowserObject.name = "FileBrowser";
		FileBrowser fileBrowserScript = fileBrowserObject.GetComponent<FileBrowser>();
		fileBrowserScript.SaveFilePanel(this, "SaveFileUsingPath", "MyLevels", "json");
	}

public void LoadFromJson() {
		GameObject fileBrowserObject = Instantiate(FileBrowserPrefab, this.transform);
		fileBrowserObject.name = "FileBrowser";
		FileBrowser fileBrowserScript = fileBrowserObject.GetComponent<FileBrowser>();
		fileBrowserScript.OpenFilePanel(this, "LoadFileUsingPath", "json");`

in this case "this" is an Empty at 0,0,0 with the script attached.

**Comment by as3mbus** [comment]
did u set the ui scale mode to "scale with screen size"  on the canvas scaler ? since it scale based on canvas size *CMIIW .

**Comment by TheRealCatherine** [comment]
Good catch! That does correct the issue for now, if we end up needing other kind of sizing options later I'll put it in as a feature request. Thanks!

**Comment by GracesGames** [comment]
Thanks for the quick response @as3mbus 👍 
Will close this issue for now then, keeping it in mind (maybe add a scaling feature in the future).
